apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: tlq2cldqi-python 
  janus-idp.io/tekton: tlq2cldqi-python
  backstage.io/kubernetes-id: tlq2cldqi-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tlq2cldqi-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml