apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: tlq2cldqi-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tlq2cldqi-python 
  name: tlq2cldqi-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: tlq2cldqi-python 
